repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    - id: ruff-format
      types_or: [ python, pyi ]

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
      args: [ -- ]
    - id: cargo-check
    - id: clippy
      args: [ --, -D, warnings ]